"""Rebuild the one-file installer from reviewed project source files."""
from pathlib import Path
import pprint

root = Path(__file__).resolve().parent
names = ('lyrics.py', 'spicy_bridge.py', 'slyrics-bridge.js', 'install.py')
files = {name: (root / name).read_text(encoding='utf-8') for name in names}
header = '''# Generated by build_installer.py. Sources are embedded below as text.
# Installs the local bridge, backs up existing files, and runs spicetify apply.
import runpy
from pathlib import Path
import tempfile

'''
footer = '''

if __name__ == "__main__":
    with tempfile.TemporaryDirectory(prefix="slyrics-install-") as temp:
        directory = Path(temp)
        for name, source in FILES.items():
            (directory / name).write_text(source, encoding="utf-8")
        runpy.run_path(str(directory / "install.py"), run_name="__main__")
'''
(root / 'install_spicy_bridge.py').write_text(
    header + 'FILES = ' + pprint.pformat(files, width=110, sort_dicts=False) + footer,
    encoding='utf-8'
)
