"""Rebuild the one-file installer from reviewed project source files."""
from pathlib import Path
import pprint

root = Path(__file__).resolve().parent
names = ('lyrics.py', 'spicy_bridge.py', 'slyrics-bridge.js', 'install.py')
files = {name: (root / name).read_text(encoding='utf-8') for name in names}
header = '''# Generated by build_installer.py. Sources are embedded below as text.
# Installs the local bridge, backs up existing files, and runs spicetify apply.
import runpy
from pathlib import Path
import tempfile

'''
footer = '''

if __name__ == "__main__":
    with tempfile.TemporaryDirectory(prefix="slyrics-install-") as temp:
        directory = Path(temp)
        for name, source in FILES.items():
            (directory / name).write_text(source, encoding="utf-8")
        runpy.run_path(str(directory / "install.py"), run_name="__main__")
'''
(root / 'install_spicy_bridge.py').write_text(
    header + 'FILES = ' + pprint.pformat(files, width=110, sort_dicts=False) + footer,
    encoding='utf-8'
)

# A distinct download name avoids accidentally reusing the original installer.
repair_header = '''# Generated by build_installer.py: repair the installed Python files only.
from pathlib import Path
import datetime
import os
import shutil
import subprocess
import sys

'''
repair_footer = '''

def repair():
    target = Path.home() / ".local/share/spotify-live-lyrics"
    if not (target / "bridge-config.json").is_file():
        raise RuntimeError("Ponte não instalada aqui. Execute install_spicy_bridge.py primeiro.")
    for name, source in FILES.items():
        compile(source, name, "exec")
    stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S-%f")
    backup = target / "backup" / ("before-fallback-fix-" + stamp)
    backup.mkdir(parents=True)
    for name, source in FILES.items():
        destination = target / name
        if destination.exists():
            shutil.copy2(destination, backup / name)
        temporary = target / (name + ".repair-tmp")
        temporary.write_text(source, encoding="utf-8")
        os.replace(temporary, destination)
        if destination.read_text(encoding="utf-8") != source:
            raise RuntimeError("Falha ao verificar " + str(destination))
    # Check the installed module, using a new interpreter rather than cached imports.
    check = "import sys; sys.path.insert(0, sys.argv[1]); import spicy_bridge as b; assert hasattr(b, 'Fallback'); assert callable(b.choose_body)"
    subprocess.run([sys.executable, "-c", check, str(target)], check=True)
    print("Correção instalada e verificada: fonte antiga automática + digitação contínua.", flush=True)
    print("Backup:", backup, flush=True)
    if "--install-only" not in sys.argv:
        print("Abrindo o arquivo corrigido diretamente. Para sair: Ctrl+C.", flush=True)
        try:
            subprocess.run([sys.executable, str(target / "lyrics.py")], check=True)
        except KeyboardInterrupt:
            pass


if __name__ == "__main__":
    try:
        repair()
    except (OSError, RuntimeError, subprocess.CalledProcessError) as error:
        print("Correção não concluída:", error)
        sys.exit(1)
'''
(root / 'corrigir_slyrics_fallback_v3.py').write_text(
    repair_header + 'FILES = ' + pprint.pformat(
        {name: files[name] for name in ('lyrics.py', 'spicy_bridge.py')},
        width=110, sort_dicts=False) + repair_footer, encoding='utf-8'
)
