complete -c sylrics -f
complete -c sylrics -n '__fish_use_subcommand' -a 'play demo config theme source visualizer control doctor cache bridge' -d 'sylrics command'
complete -c sylrics -l source -xa 'native auto spicy' -d 'Lyric source'
complete -c sylrics -l config -r -d 'Alternative INI file'
complete -c sylrics -l version -d 'Version'
complete -c sylrics -n '__fish_seen_subcommand_from config' -a 'path list get set edit'
complete -c sylrics -n '__fish_seen_subcommand_from theme' -a 'warm purple mono ocean'
complete -c sylrics -n '__fish_seen_subcommand_from cache' -a 'info clear'
complete -c sylrics -n '__fish_seen_subcommand_from bridge' -a 'install status'
complete -c sylrics -n '__fish_seen_subcommand_from get set' -a 'playback.source playback.player playback.fps playback.sync_offset playback.type_ahead pages.mode pages.min_lines pages.max_lines pages.target_seconds pages.pause_seconds layout.alignment layout.vertical layout.padding layout.line_spacing layout.lyrics_width layout.show_source layout.show_footer layout.show_progress layout.border layout.icons layout.cursor visualizer.mode visualizer.style visualizer.width visualizer.height visualizer.only_gaps visualizer.input visualizer.sensitivity colors.accent colors.text colors.background colors.border colors.muted'
